### ISSUE TITLE
SearchResult<T> is missing NbHits & ExhaustiveNbHits fields.

### ISSUE THREAD

**Issue by bzatrok** [meilisearch/meilisearch-dotnet#109]
SearchResult<T> is missing NbHits & ExhaustiveNbHits fields. These are returned by the api but not mapped to the response object.

**Comment by bzatrok** [comment]
@curquiza Let me know if this can be closed after the nuget build is done!

**Comment by curquiza** [comment]
I published the release! 😄 
I close this!

**Comment by curquiza** [comment]
Thanks for your help @bzatrok
