### ISSUE TITLE
Implement GetKeys method

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#122]
Create `GetKeys` according to this route: https://docs.meilisearch.com/reference/api/keys.html#get-keys

**Comment by gethari** [comment]
@curquiza I thought of picking this up and I have some suggestions to improve the SDK. Currently, the file alignment is spread in the root, all the `Models` , `Extensions` and `Client` everything is kept outside. Would it be ok, if we create a structured approach either follow `stack` driven design or `domain` driven?

Eg : We can have all response folders under `Models`. In the future, as the Meilisearch grows if there will be a lot more APIs (assuming ) it will be quite hefty seeing all files outside. I can raise a PR along with this route implementation if that's ok with you 😃

**Comment by curquiza** [comment]
Thanks for your suggestion @gethari!

FYI, MeiliSearch will not add so many routes 🙂 I agree with improving the current structure of this SDK but it should not be too complex regarding the goal of the SDK.
I really would like to concretely see what you mean with a PR, if you have time of course, because I cannot guarantee we will merge it. But if it helps us for the maintenance it would be awesome!!
Another really important rule when refactoring: the usage of the SDK, I mean the README and the usage of methods, must stay unchanged 🙂

**Comment by curquiza** [comment]
Closed in favor of this PR https://github.com/meilisearch/meilisearch-dotnet/pull/217. WIll be released in meilisearch-dotnet v0.9.0
