### ISSUE TITLE
Implement sub-settings methods

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#124]
Currently only `GetSettings`,  `UpdateSettings` and `ResetSettings` are implemented. These routes manage all the settings by calling this ["general" settings route](https://docs.meilisearch.com/reference/api/settings.html).

But currently in this SDK, no method are implemented to call the sub-routes of each settings.
We need to add the `GetXXX`, `UpdateXXX` and `ResetXXX` where `XXX` are the following settings:
- [ ] [Ranking rules](https://docs.meilisearch.com/reference/api/ranking_rules.html)
- [ ] [Synonyms](https://docs.meilisearch.com/reference/api/synonyms.html)
- [ ] [Stop-words](https://docs.meilisearch.com/reference/api/stop_words.html)
- [ ] [Searchable attributes](https://docs.meilisearch.com/reference/api/searchable_attributes.html)
- [x] [Displayed attributes](https://docs.meilisearch.com/reference/api/displayed_attributes.html)
- [ ] [Attributes for faceting](https://docs.meilisearch.com/reference/api/attributes_for_faceting.html)
- [ ] [Distinct attribute](https://docs.meilisearch.com/reference/api/distinct_attribute.html)

⚠️ Tests should be added for each method

No need to do all the settings in the same PRs of course, any contributions, even small, are welcome 😇❤️
Feel free to ask any question!

**Comment by themisir** [comment]
I can work on this issue in coming days or maybe a week later.

**Comment by tjakubo** [comment]
Can I work on this?
Possibly submitting a PR with a single sub-setting first, to make sure I got the basics right (and if all is OK or fixed, then the rest).

**Comment by curquiza** [comment]
Hello @tjakubo2 
Yes you can work on this. 
It's indeed a good idea to do a first PR with one and the rest in another one 🙂
