### ISSUE TITLE
Creating/Deleting indexes in meilisearch server results in IP down

### ISSUE THREAD

**Issue by Vijay4657** [meilisearch/meilisearch-dotnet#127]
We are trying to create new index or delete existing from the client using the below code.

Create index using below methods
```
MeilisearchClient client = new MeilisearchClient(ConfigurationManager.AppSettings["SearchURL"],ConfigurationManager.AppSettings["SearchKey"]);
var newIndex = await client.CreateIndex("testing");
var Index = await client.GetOrCreateIndex("testing").ConfigureAwait(false);
```

While calling the above methods to create the index, the hosted URL(SearchURL) goes down result in the timeout. We then have to start/stop the meilisearch server to enable the hosted URL to access the search. We are using the nuget Meilisearch Dotnet version - 0.4.2.(Meilisearch version 0.20.0) Meilisearch server in which we have hosted the SearchURL is in OS:Debian we have Same problem arises while deleting any of the existing index as well.

Anyone have an idea regarding this.?

**Comment by curquiza** [comment]
Hello! Did you push documents to MeiliSearch before executing these 3 lines of code?

**Comment by Vijay4657** [comment]
Hi @curquiza 

Yes, i have pushed documents to the indexes which was created before.. While trying to create new index only this problem arises.

**Comment by curquiza** [comment]
It's not due to this SDK, this is related to MeilISearch.
How many documents have you pushed?

**Comment by Vijay4657** [comment]
We have pushed in the set of 100 documents each update. But that was in the existing index.

**Comment by curquiza** [comment]
Not sure to understand, you pushed only 100 documents before? There is no other documents in the existing index?

**Comment by curquiza** [comment]
I ask this because the issue you have seems to have happens when adding too many documents to MeiliSearch at the same time: MeiliSearch crashes and you cannot access it without re-launching it.
But 100 documents in MeiliSearch is really few.

**Comment by curquiza** [comment]
Closing due to lack of answer. Feel free to re-open if needed :)
