### ISSUE TITLE
Method to get all the indexes should return a list of instance

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#155]
Currently, the `get_all_indexes` method returns a raw list of object, but not a list of `Index` instance. This is the only index-related method that does not return an `Index` instance.

An instance is more convenient to manipulate than a raw object. See this [example](https://github.com/meilisearch/meilisearch-python/issues/258#issuecomment-835866135).

TODO

- [x] Change the return of the current `get_all_indexes`: make it return a list of `Index` instances
- [ ] Provide `get_all_raw_indexes`: a method that returns the list of object of indexes, so the response of the MeiliSearch server.
- [ ] Add tests

⚠️ No code duplication: use `get_all_raw_indexes` in `get_all_indexes`.

Related to https://github.com/meilisearch/integration-guides/issues/122

⚠️ Also, this issue is generated, and `get_all_indexes` might be named differently in this package. Keep the already existing way of naming in this package to stay idomatic with the language and the repository.

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue.

**Comment by nico91470** [comment]
Hi,

I want to try to resolve this issue, can you affect me on it?

**Comment by curquiza** [comment]
Please go @nico91470 :)

**Comment by curquiza** [comment]
@nico91470 I will remove the assignation since we don't get any PR from you, we can understand you don;t have the time 🙂

Now, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the real volunteers contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/meilisearch-js/blob/main/CONTRIBUTING.md).

**Comment by Vivek-abstract** [comment]
Hi @curquiza, I think this is already implemented as seen here:
https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/MeilisearchClient.cs#L82

**Comment by Vivek-abstract** [comment]
Please correct me if I'm looking at the wrong thing here

**Comment by curquiza** [comment]
Oh yes you're right the first point is already implemented! :D

**Comment by Vivek-abstract** [comment]
@curquiza  I've created https://github.com/meilisearch/meilisearch-dotnet/pull/178 to add this method 😄
