### ISSUE TITLE
Refactor the way of handling HTTP request?

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#167]
In https://github.com/meilisearch/meilisearch-dotnet/pull/165 I implemented an `HttpRequest` class to implement our own HTTP methods (`PostAsJsonAsync`...) to remove the `charset-utf8` content type.

However, I'm not a c# dev, and I feel like I missed something: at first I wanted to "extend" the `HttpClient` class and override `PostAsJsonAsync`, but without any success. So I came to the current implementation you can find in the `main` branch.

Does anyone know a better way to implement this?

Feel free to open any PR!

**Comment by jdkramhoft** [comment]
Will the content-type ever need to be charset-utf8? Or would it be fine to set the content type of all requests with json body as empty?

**Comment by curquiza** [comment]
For `POST` and `PUT` requests, the content type must not contain `charset-utf8`.
MeiliSearch only accepts `application/json` as `content-type`
For the [documents routes](https://docs.meilisearch.com/reference/api/documents.html#documents), `application/x-ndjson` and `text/csv` can also be accepted additionally to  `application/json`

**Comment by Vivek-abstract** [comment]
@curquiza  I'd like to take this on. Let me see if I can find a way to use the existing HttpClient and extend it

**Comment by Vivek-abstract** [comment]
@curquiza  I've created https://github.com/meilisearch/meilisearch-dotnet/pull/172 for this
