### ISSUE TITLE
Missing routes need to be implemented

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#17]
Some routes present in MeiliSearch are not implemented in this package yet:
- [X] The global settings routes: https://docs.meilisearch.com/references/settings.html
- [ ] The settings sub-routes: https://docs.meilisearch.com/references/settings.html
- [x] All the health routes: https://docs.meilisearch.com/references/health.html
- [x] The global stats route: https://docs.meilisearch.com/references/stats.html#get-stats-of-all-indexes
- [x] The index stats route: https://docs.meilisearch.com/references/stats.html#get-stat-of-an-index

The settings routes and sub-routes are the most urgent ones 🙂

⚠️ Tests should be added for each newly implemented route.

**Comment by Nothing-Works** [comment]
@curquiza I can try this one if no one has started yet.

**Comment by curquiza** [comment]
Hello @Nothing-Works!
Sure you can!! 😁 Thanks!

**Comment by satish860** [comment]
@Nothing-Works Assigned the task to your name so no one else starts on this. Hope that is fine.

**Comment by Nothing-Works** [comment]
@satish860 this is all good, thanks, I will start soon.

**Comment by curquiza** [comment]
Hello @Nothing-Works!
How are you doing on your issue? 🙂 Do you need help?
Another contributor or maintainer can implement a part of this issue if you don't find any time to do it 😉

**Comment by Nothing-Works** [comment]
@curquiza Hi I am very very sorry, about this issue. I've been so busy and just a lot of things happening in my area. Please feel free to give this task to another maintainer. Again apologize for my problems, I should have let you know earlier. I am so sorry, hope you can understand. Thank you very much.

**Comment by curquiza** [comment]
Not a problem! Thanks for your quick answer! 🙂

If any contributor is available for this issue (or a part of it) it would be really helpful 😁

**Comment by themisir** [comment]
I started working on this. And finished. But I need a bit help about MeiliSearch related issues. (Some routes doesn't works as expected - or as described in docs)

**Comment by curquiza** [comment]
Hello @TheMisir!
I'm working on the [3 global settings routes](https://docs.meilisearch.com/references/settings.html#all-settings) (get/update/reset) in this PR https://github.com/meilisearch/meilisearch-dotnet/pull/57. GitHub did not do the link to this issue despite my mention in the PR description, sorry.
But the rest still needs to be implemented, so thanks a lot!! 😁

**Comment by themisir** [comment]
> Hello @TheMisir!
> I'm working on the [3 global settings routes](https://docs.meilisearch.com/references/settings.html#all-settings) (get/update/reset) in this PR #57. GitHub did not do the link to this issue despite my mention in the PR description, sorry.
> But the rest still needs to be implemented, so thanks a lot!! 😁

So, what should I do now 😅?

PS: I completed implementing routes (routes / inline docs / tests). I just have a small issue (please check comments on my PR) which requires a bit help. But as you've already implemented settings routes (which my issue is related to) I think we could somehow merge our codes together.

**Comment by curquiza** [comment]
I inform you only to avoid duplication on the 3 global settings routes, but your work on stats routes and health routes is perfect! 👍
We are going to merge #58, #58 and then #57 before your PR, it will be easier. But of course, you can still keep working on it even if we merge it after them 🙂

I will check your PR on Monday and try to help you 😁 Thanks again for your contribution to this!!

**Comment by curquiza** [comment]
@TheMisir I don't know if you are already on our slack, but [you can join us](https://meilicommunity.slack.com/join/shared_invite/zt-c4rs8tpi-ZId_q3fw~7cqeuzFG4XHaA#/). If you agree, it would be easy to discuss about contributions 🙂 I'm Clementine on our Slack!

**Comment by curquiza** [comment]
I've just merged #57 that includes the [global settings methods](https://docs.meilisearch.com/references/settings.html#all-settings)
- `GetAllSettings`
- `UpdateAllSettings`
- `ResetAllSettings`

Still missing the sub-routes for settings

**Comment by curquiza** [comment]
Thanks to @TheMisir and #66, the three last points are completed!! 🎉

**Comment by curquiza** [comment]
Replaced by #122 and #124
