### ISSUE TITLE
Remove Microsoft.AspNetCore.WebUtilities to increase the surface area of the project

### ISSUE THREAD

**Issue by sander1095** [meilisearch/meilisearch-dotnet#176]
Hello!

I was having a peek at the dependencies of this project, and I encountered the `Microsoft.AspNetCore.WebUtilities` dependency. This dependency has itself 2 dependencies on other projects..

What is the reason for this package? As far as I can see, it is only used to generate some query strings:
https://github.com/meilisearch/meilisearch-dotnet/blob/8d5b14cc2a12a407b88ee4f9b41c0b80bf6c6548/src/Meilisearch/Index.cs#L129

I believe these do not belong in this library for several reasons:

- I see this library as general purpose; any type of project should be able to use it. So why do we have an `AspNetCore` package dependency? 
- Why introduce a dependency to generate some `?query=strings&and=stuff`? :) This can easily be done with normal C#.

Removing this dependency will increase the surface area that cna be reached with this library because it needs fewer dependencies to function and could increase adoption by removing a "wonky" dependency :)

**Comment by sander1095** [comment]
I think I created this issue a bit too quick! 

Some more research needs to be done and I think some more discussions need to take place before this is picked up.

The source code of the `QueryHelpers` class is as follows:

https://github.com/dotnet/aspnetcore/blob/main/src/Http/WebUtilities/src/QueryHelpers.cs
You can see it's a bit "enterprisey", but it does also do things like encoding URLS and all that stuff. If we care about that (which I think we do), we'd need more custom code to fill that hole with...

Read some more info about this namespace here: https://github.com/dotnet/aspnetcore/tree/main/src/Http

I do still feel a bit odd about having a dependency with aspnetcore in it's name, because it  feels kind of internal to the ASP net core project and out of place here?

In any case, I guess this issue can just be closed by the maintainers if they feel this is irrelevant for now.. Otherwise, I am curious what you guys have to say!

**Comment by curquiza** [comment]
Hello @sander1095!
Thanks for bringing this kind of discussion, we particularly appreciate it :)
I'm not an expert in .NET projects, so I will let this issue open: I would enjoy reading the .NET community opinion about this!

**Comment by juchom** [comment]
@sander1095 is right, you don't need to take a dependency on AspNetCore for this.

You don't need all the stuff in it just for a few lines of code and the base framework offers the escape method `Uri.EscapeDataString`.

I've made a PR for this.

**Comment by curquiza** [comment]
Thanks @juchom for your involvement as well! :)
