### ISSUE TITLE
`UpdateIndex()` method

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#179]
TODO:
- [ ] Currently we have the `UpdateIndex()` method in the [`Index` class](https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/Index.cs). This method should be renamed as `Update()`.
- [ ] Add a method named `UpdateIndex()` in the [`Client` class](https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/MeilisearchClient.cs), calling the `Update()` newly created in `Index`.
- [ ] Add tests and adapt the current ones.

**Comment by GrillSkippy** [comment]
Hi, could you assign this issue to me?

**Comment by curquiza** [comment]
Hello @JaspervdGraaf thanks for your interest in this project :)

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/meilisearch-dotnet/blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 🙂
