### ISSUE TITLE
Use ConfigureAwait(false) to improve performance of the library

### ISSUE THREAD

**Issue by sander1095** [meilisearch/meilisearch-dotnet#181]
Please read:

https://github.com/Microsoft/vs-threading/blob/main/doc/cookbook_vs.md#should-i-await-a-task-with-configureawaitfalse
https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

Not using `ConfigureAwait(false)` in a library that might be used by an app that has a SynchronizationContext could result in a loss of performance and perhaps some issues.

This library should use `ConfigureAwait(false)` everywhere to prevent this

**Comment by curquiza** [comment]
Thank you @sander1095 for these resources. Indeed this is something we should consider!
Feel free to open PR if you want and have the time to :)
