### ISSUE TITLE
NDJSON/CSV methods to add and update documents

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#182]
⚠️ This issue is generated, it means the nameing might be done differently in this package (ex: `add_documents_json` instead of `addDocumentsJson`). Keep the already existing way of naming in this package to stay idiomatic with the language and this repository.

📣 We strongly recommend doing multiple PRs to solve all the points of this issue

[MeiliSearch v0.23.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.23.1) introduces two changes:
- new valid formats to push data files, additionally to the JSON format: CSV and NDJSON formats.
- it enforces the `Content-type` header for every route requiring a payload (`POST` and `PUT` routes)

---

Here are the expected changes to completely close the issue:

- [x] Currently, the SDKs always send `Content-Type: application/json` to every request. Only the `POST` and `PUT` requests should send the `Content-Type: application/json` and not the `DELETE` and `GET` ones.

- [x] Add the following methods and 🔥 **the associated tests** 🔥 to ADD the documents. Depending on the format type (`csv` or `ndjson`) the SDK should send `Content-Type: application/x-dnjson` or `Content-Type: text/csv`)
  - [x] `addDocumentsJson(string docs, string primaryKey)`
  - [x] `addDocumentsCsv(string docs, string primaryKey)`
  - [x] `addDocumentsCsvInBatches(string docs, int batchSize, string primaryKey)`
  - [x] `addDocumentsNdjson(string docs, string primaryKey)`
  - [x] `addDocumentsNdjsonInBatches(string docs, int batchSize, string primaryKey)`

- [x] Add the following methods and 🔥 **the associated tests** 🔥 to UPDATE the documents. Depending on the format type (`csv` or `ndjson`) the SDK should send `Content-Type: application/x-dnjson` or `Content-Type: text/csv`)
  - [x] `updateDocumentsJson(string docs, string primaryKey)`
  - [x] `updateDocumentsCsv(string docs, string primaryKey)`
  - [x] `updateDocumentsCsvInBatches(string docs, int batchSize, string primaryKey)`
  - [x] `updateDocumentsNdjson(string docs, string primaryKey)`
  - [x] `updateDocumentsNdjsonInBatches(string docs, int batchSize, string primaryKey)`

`docs` are the documents sent as `String`
`primaryKey` is [the primary key of the index](https://docs.meilisearch.com/learn/core_concepts/indexes.html#primary-key)
`batchSize` is the size of the batch. Example: you can send 2000 documents in raw String in `docs` and ask for a `batchSize` of 1000, so your documents will be sent to MeiliSearch in two batches.

Example of PRs:
- in PHP SDK: https://github.com/meilisearch/meilisearch-php/pull/235
- in Python SDK: https://github.com/meilisearch/meilisearch-python/pull/329

----------

Related to: https://github.com/meilisearch/integration-guides/issues/146

If this issue is partially/completely implemented, feel free to let us know.

**EDIT**:

The files needed for the tests when creating the csv and ndjson methods are available here:
- [songs.csv](https://github.com/meilisearch/meilisearch-python/blob/main/datasets/songs.csv)
- [songs.ndjson](https://github.com/meilisearch/meilisearch-python/blob/main/datasets/songs.ndjson)

**Comment by iverburgh** [comment]
Currently working on this issue

**Comment by curquiza** [comment]
Hello @iverburgh 

Thanks for your interest in this project :)

Just FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/meilisearch-dotnet/blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 🙂

**Comment by juchom** [comment]
Hello @curquiza 

I'm having a look at this issue and the first item to fix it this one


> Currently, the SDKs always send Content-Type: application/json to every request. Only the POST and PUT requests should send the Content-Type: application/json and not the DELETE and GET ones.

Can you point me some code where GET or DELETE calls are sending `Content-Type` ?

I runned the tests with Fiddler and I have this for the calls I have checked :

GET
![image](https://user-images.githubusercontent.com/17902415/148787476-4422d60e-545b-4664-9359-c364c08c249f.png)

DELETE
![image](https://user-images.githubusercontent.com/17902415/148787534-300fe49d-1084-4e40-9aba-9a21a20dfb64.png)

**Comment by curquiza** [comment]
Hello @juchom 

sorry it's indeed not the case sorry! It has been fixed!

**Comment by alallema** [comment]
Well Done @juchom 🎉
