### ISSUE TITLE
MeilisearchApiErrorContent

### ISSUE THREAD

**Issue by mrmaxonline** [meilisearch/meilisearch-dotnet#187]
Wrong JsonPropertyName's

Error result from server 0.24 (example) is:

`{"message":"Index `asdfasdf` not found.","code":"index_not_found","type":"invalid_request","link":"https://docs.meilisearch.com/errors#index_not_found"}`

**Comment by curquiza** [comment]
Hello @mrmaxonline

As the error describes, it means you try to access to your index `asdfasdf` but it does not exist.

**Comment by mrmaxonline** [comment]
Hi @curquiza 

The problem is not in the absence of an index, but in handling the exception, where properties are not substituted except for the message because they are incorrectly described with the class.

Look in MeilisearchApiErrorContent.cs:

It seems to me that the following code

`
        /// <summary>
        /// Gets or sets the errorCode.
        /// </summary>
        [JsonPropertyName("errorCode")]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Gets or sets the errorType.
        /// </summary>
        [JsonPropertyName("errorType")]
        public string ErrorType { get; set; }

        /// <summary>
        /// Gets or sets the errorLink.
        /// </summary>
        [JsonPropertyName("errorLink")]
        public string ErrorLink { get; set; }`

must be

`
        /// <summary>
        /// Gets or sets the errorCode.
        /// </summary>
        [JsonPropertyName("code")]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Gets or sets the errorType.
        /// </summary>
        [JsonPropertyName("type")]
        public string ErrorType { get; set; }

        /// <summary>
        /// Gets or sets the errorLink.
        /// </summary>
        [JsonPropertyName("link")]
        public string ErrorLink { get; set; }`

After changing the source in my project, the error began to be processed correctly

**Comment by curquiza** [comment]
Are you using MeiliSearch `v0.24.0rc0`?

**Comment by curquiza** [comment]
Oh yes, that what you meant with `Error result from server 0.24 (example) is:`

FYI, this package only works with the latest stable version of MeiliSearch which is `v0.23.1` currently, see: https://github.com/meilisearch/meilisearch-dotnet#-compatibility-with-meilisearch

We wait for the official and stable release of v0.24.0 before merging this branch (https://github.com/meilisearch/meilisearch-dotnet/pull/188) containing the change related to the error handler.

**Comment by mrmaxonline** [comment]
Perhaps this library needs to add a check for the server version in order to correctly exchange different package structures

**Comment by curquiza** [comment]
Since MeiliSearch is not stable this is something we don't want to do, but probably in the future when MeiliSearch will be stable

**Comment by curquiza** [comment]
I close this issue since an answer has been given. Feel free to re-open if needed
