### ISSUE TITLE
Suffix async methods with Async

### ISSUE THREAD

**Issue by juchom** [meilisearch/meilisearch-dotnet#196]
Today .NET ecosystem suffix all asynchronous methods with Async.

Since the client .net client is currently all async it would be good to suffix this methods with Async.

This would leave space to create a sync api if needed for some users.

Also, passing CancellationToken and propagating it to httpclient would be a good idea.

**Comment by curquiza** [comment]
Hello @juchom!

thanks for this suggestion, this would be indeed a good addition! Plus, we are not stable yet, so that is the perfect time to do it!

PRs are welcome :)

**Comment by juchom** [comment]
This can be done the hard way, just suffix every methods with `Async`
Then recreate sync methods after.

A more friendly way would be to use the `Obsolete` attribute on old methods and leave a message for developpers, but break during builds. Then in  a second time recreate the sync api.

First one is more time efficient, can be done in one release.
Second one is less time efficient, but more user friendly. 1st version would deprecate old methods with friendly messages. 2nd version would replace old methods with sync one.

**Comment by curquiza** [comment]
I think I would rather the first version. Since we are not stable, we can do it this way :)

**Comment by curquiza** [comment]
Sorry I thought I answered your comment!!
I agree with the hard way
