### ISSUE TITLE
APIs are called at the root path

### ISSUE THREAD

**Issue by Nextra** [meilisearch/meilisearch-dotnet#198]
**Description**
When providing the `HttpClient` with a `BaseAddress` that has a path such as https://example.com/api/meilisearch, MeiliSearch .NET will call most APIs at the root path regardless - for example https://example.com/health instead of https://example.com/api/meilisearch/health.

**Expected behavior**
MeiliSearch should respect the `BaseAddress` path instead of forcing calls directly against the root.

**Current behavior**
APIs are mostly called like this: `await this.http.GetAsync("/health")` which causes them to always run against the root.
They should be called like this: `await this.http.GetAsync("health")`

There are also isolated cases where it is already done as expected, causing those calls to behave differently than most of the others: https://github.com/meilisearch/meilisearch-dotnet/blob/3137b00ebc62766a75eca947eb990e6904e09295/src/Meilisearch/Index.cs#L98

**Comment by alallema** [comment]
HI @Nextra,
Thank you for taking the time to write about this issue. This repo is maintained by @curquiza, they are on holiday and will check it when they are coming back.

**Comment by Nextra** [comment]
Understood @alallema.

Should anyone else stumble across this in the meanwhile, here is a quick and dirty fix by using a message handler that patches the request URI (if necessary) before letting MeiliSearch handle it as usual:

```c#
class FixMessageHandler : MeilisearchMessageHandler
{
    public FixMessageHandler(HttpMessageHandler innerHandler)
        : base(innerHandler)
    {
    }

    protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var endpoint = new Uri("https://example.com/api/meilisearch");

        if (!endpoint.IsBaseOf(request.RequestUri)) {
            request.RequestUri = new Uri(endpoint, request.RequestUri.PathAndQuery.TrimStart('/'));
        }

        return await base.SendAsync(request, cancellationToken);
    }
}
```

**Comment by curquiza** [comment]
Hello @Nextra

Thanks for this issue!
This is indeed something we might need to handle in this SDK: not only the API root path should be accepted.

PR are welcomed, containing tests 🔥

**Comment by Nextra** [comment]
For context: If this SDK is to be used on a client - where MeiliSearch is almost guaranteed to sit behind a reverse proxy - it is completely unusable out of the box.
