### ISSUE TITLE
Update logo with the latest .NET

### ISSUE THREAD

**Issue by juchom** [meilisearch/meilisearch-dotnet#204]
The current logo on the README.md file is the one from the old .Net Framework.

The new one can be found here : https://en.wikipedia.org/wiki/.NET_Framework

Ok, not the most important fix :)

**Comment by curquiza** [comment]
Hello @juchom 

Thanks for this issue. Every issue, even this tiny one, is a contribution for us, thanks 🙂

I will change it asap!
