### ISSUE TITLE
Reduce the memory pressure of JSON using Streaming extensions.

### ISSUE THREAD

**Issue by satish860** [meilisearch/meilisearch-dotnet#21]
As the library manipulates JSON data, Its the best practices to use it as a stream rather than holding the entire memory for the same. More details can be found here. 
https://www.stevejgordon.co.uk/sending-and-receiving-json-using-httpclient-with-system-net-http-json

**Comment by curquiza** [comment]
Thanks Satish for this issue! :)
Will this improvement change the way of using meilisearch-dotnet? I mean is the getting started going to change after this improvement? 🙂

**Comment by satish860** [comment]
No @curquiza Its only internal change.
