### ISSUE TITLE
Adopt a new style guide

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-dotnet#216]
Add a new and consistent styling to the project.

- [ ] Adopt new and the most spread style guidelines for C#
- [ ] The new style guide should be guarded with an automated tool that could be integrated with our CI
- [ ] We should have a way to explain to users these new guidelines without bikeshedding.

--- 
## initial issue (before the discussions)
Old issue title: **Make the types explicit instead of using var's everywhere**

This idea came from this code review https://github.com/meilisearch/meilisearch-dotnet/pull/215#discussion_r786077142

According to [Microsoft's good practice guides](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#implicitly-typed-local-variables) is not good to have `var variable = SomethingYouDontReallyKnowTheReturn();`. 

In order to prevent this from happen this issue talks about removing all of the `var` from:

- [ ] Documentation (eg. code-samples)
- [ ] Source Code
- [ ] Comments
- [ ] Tests

With the concept in mind about **only changing when the type on the right side of the statement is not clear** like the guide says.

Use common sense in order to achieve the best readability possible during the refactor! ;)

**Comment by juchom** [comment]
This guidelines are taken from the runtime coding style

https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateManaged/HuffmanTree.cs

If you look at how Microsoft is developing aspnet core, it looks like they go all the way with var

https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs

Or StackExchange.Redis

https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateManaged/HuffmanTree.cs

Maybe going the way how aspnet core or other big OSS project are written would be easier for contributors who are used to the `var` keyword.

**Comment by brunoocasali** [comment]
Hello @juchom, thank you again for being so present in this repo, we really appreciate your support! ❤️ 

Reading the links you send me, make the guide even clearer, what I was trying to achieve is a good way to explain to contributors, "how the code should look like". 

So if in the community (in this case the creator of the language) we have a style guide that is adopted by them I really think that is good for us to adopt it, instead of giving them a list of repositories and saying "hey do what they are doing". 

I am really confident that is a good way to spread patterns around the source code.

I'll update the issue to add a sentence telling about using common sense during the refactor. And the idea of this issue is not to refactor everything no matter what, but yes, is just to improve the readability by using types when the right side of the assignment is not so clear.

For example in these cases I agree with the usage of `var` keyword because is clear for me what is the type:  

- [L72](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L72)
  ```cs
   var list = new List<KeyValuePair<string, object?>>(...)
  ```
- [L126](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L126)
  ```cs
  var httpRequestLog = new HttpRequestLog(list);
  ```  
But not in this one:

- [L136](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L136)
  ```cs
  var response = context.Response;
  ```  
 
So, feel free to raise your concerns about it, I really appreciate your attention (and sorry for the late reply)

**Comment by juchom** [comment]
I, personally, would stick to asp.net core coding styles because it has been widely adopted.

The runtime repo is a bit different from all others from Microsoft, probably because they really want to have really explicit code in order to avoid some side effects the `var` keyword would hide after some refactoring for exemple.

The other reason, is nowadays coding assistants are giving a lot of help and information. I'm not sure replacing `var` with `HttpResponse` would bring anything to developpers.

```csharp
var response = context.Response;

HttpResponse response = context.Response;
```

If you don't know the type behind the `var`, you will always use intellisense or other coding assistants to see what's in it.

I find it also easier to read and avoid the mix of `var` and `TypeOfObject`. I would avoid this mix, just go all `var` or all `TypeOfObject`.

**Comment by anthkernan-dev** [comment]
I would vote for var - it's what most developers are going to be used too and Microsoft themselves recommend this style when the type is obvious from the assignment - if you need to have certainty on the type then be explicit, otherwise don't.

**Comment by juchom** [comment]
I saw that you are mixing `StyleCop` rulesets and `.editorconfig`.

I would strongly suggest to remove rulesets and move them to `.editorconfig`, you will have a central point for configuring everything.

**Comment by sander1095** [comment]
I vote for var. I would say that var should be the default, and if a type is unclear, we use the explicit type :). `var` is definitely the default in the industry

**Comment by juchom** [comment]
I can open a PR with the asp.net core coding style and leave it for review.

This PR will have to be merged fast because every file will be modified. If you're ok with that, just let me know when you have time for the review.

**Comment by juchom** [comment]
Ok, I just made a test to see how it will go and I think, it will be better to do some iterations.

For the first step, I would completely remove `StyleCop` from the projects because it doesn't play well with `.editorconfig`. This will help us define the rules we want and we may reintroduce it later if `.editorconfig` is not enough.

I would enable `C#10` in order to have file scoped namespace, this will reduce the tabs.

And move usings at the top of the file.

This will look like more modern C# style. Having `using` inside `namespace` is from .NET Framework 2.0 era :)

```csharp
namespace Meilisearch
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Wrapper for index stats.
    /// </summary>
    public class Stats
    {
        /// <summary>
        /// Gets or sets database size.
        /// </summary>
        public int DatabaseSize { get; set; }

        /// <summary>
        /// Gets or sets last update timestamp.
        /// </summary>
        public DateTime? LastUpdate { get; set; }

        /// <summary>
        /// Gets or sets index stats.
        /// </summary>
        public IDictionary<string, IndexStats> Indexes { get; set; }
    }
}
```

will become

```csharp
using System;
using System.Collections.Generic;

namespace Meilisearch;

/// <summary>
/// Wrapper for index stats.
/// </summary>
public class Stats
{
    /// <summary>
    /// Gets or sets database size.
    /// </summary>
    public int DatabaseSize { get; set; }

    /// <summary>
    /// Gets or sets last update timestamp.
    /// </summary>
    public DateTime? LastUpdate { get; set; }

    /// <summary>
    /// Gets or sets index stats.
    /// </summary>
    public IDictionary<string, IndexStats> Indexes { get; set; }
}
```

**Comment by brunoocasali** [comment]
> I can open a PR with the asp.net core coding style and leave it for review.
> 
> This PR will have to be merged fast because every file will be modified. If you're ok with that, just let me know when you have time for the review.

Can you open a PR modifying some files? (not every file). This way we could iterate in the comments to make sure we are in the same page regarding this theme, then you could open the PR for every other file following our new convention.

What do you think @juchom ?

**Comment by juchom** [comment]
A draft is open and I'll update it according to the reviews.

I will go rule per rule to make it easy to follow.

**Comment by sander1095** [comment]
Hello :)

I suggest running `dotnet new editorconfig` in the root of the project and overwriting/updating the exisiting one.

The generated file will contain all the default styling rules from microsoft. Running `dotnet format` and dotnet format --severity info` will then format the cofe according to those rules. 

This prevents discussions like this with manual code changes, now you can just execute one command to make the code look like it should. 

You get warnings/errors if your code is not properly formatted, which is immensely helpful in PR builds. 

My go-to editorconfig file is the one from asp.net core, it just works. And i don't really care much about specific styling, as long as it is consistent.

**Comment by brunoocasali** [comment]
Hello everyone, thanks for your suggestions here, this will make this package even better!

This issue started with one idea and your comments regarding this topic changed my mind. I don't develop in C# for a long time, and the community evolved!

I will not remove the initial suggestions, I will put a DISCLAIMER into the main description of this issue mentioning the final decision. 

Like I mentioned in @juchom's PR, what I really want in the first place is to have **consistent styling**, a **way to automate the code review regarding styling**, and a **way to explain to users how they should develop** the code (regarding the styling of course) without having to discuss about it.

@juchom can you add in your PR, some lines into the CONTRIBUTING.md talking about the styling and how they should look like? - _if you have some official references (articles, guides, repositories) it would be awesome for the contributors (and for maintainers)_ -.

**Comment by juchom** [comment]
I added a few lines and two repos that almost look like what Microsoft is doing in `asp.net core`. It's pretty difficult to have a perfect match since every developers in the end have their own styles and use different versions of `C#`.

This is a base where `StyleCop` and `.editorconfig` are not fighting, the style looks like what you will find in OSS projects.

Now, if you miss something or want something to be checked, just open an issue and we'll see if we can solve it with `.editorconfig` or a `roslyn analyzer`
