### ISSUE TITLE
Implement `client.UpdateKeyAsync()` method

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#218]
With the release of [MeiliSearch v0.25.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.25.2), and following this PR (https://github.com/meilisearch/meilisearch-dotnet/pull/217), I was not able to implement `client.UpdateKeyAsync()` method.

Looks like `Http.PatchAsync` is not available with the .NET version we are using.

I might have missed something 🙂

**Comment by juchom** [comment]
Your client is targetting .NET Standard 2 which I think is a bit old.

Would you consider updating this client to .NET Standard 2.1 ? This would solve your issue as you can see here : 
https://docs.microsoft.com/fr-fr/dotnet/api/system.net.http.httpclient.patchasync?view=net-6.0

Many libraries are dropping support for .Net Standard 2 at the moment. Meilisearch is a new product, I'm not sure you would take any advantage on sticking to this version of .NET Standard.

This also would open new .NET features that are not available right now.

**Comment by brunoocasali** [comment]
Hello, @juchom thanks for your comment!

Do you have some official information about .net versions usage? Or just good references that the .net community use for us to check in the future?

btw: I found some like [builtwith](https://trends.builtwith.com/framework/ASP.NET) and [w3techs](https://w3techs.com/technologies/details/pl-aspnet).

**Comment by juchom** [comment]
To help you decide, you first have to check the .NET Standard support here : https://docs.microsoft.com/fr-fr/dotnet/standard/net-standard

You can read the announcement here : https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

.NET Core support : https://docs.microsoft.com/en-gb/lifecycle/products/microsoft-net-and-net-core

Concerning .NET Framework support : https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-framework

>.NET Framework 4.5.2 and later follows the lifecycle policy of the underlying Windows OS on which it is installed. The support lifecycle for various versions of Windows can be found on the Windows lifecycle fact sheet.

>.NET Framework 4.8 is the latest version of .NET Framework and will continue to be distributed with future releases of Windows. As long as it is installed on a supported version of Windows, .NET Framework 4.8 will continue to also be supported.

As you can see Microsoft stopped development en classic .NET Framework and it will be distributed as a windows component.

Microsoft will drop support of 4.6.1 this year on 26 Apr 2022 and .NET Core 2 is not supported anymore.

I have no real statistics on usage except the ones you gave.

You mainly have the trade off between supporting legacy applications vs having new features for a modern client.

**Comment by curquiza** [comment]
Thanks a lot @juchom for your insight!

> Would you consider updating this client to .NET Standard 2.1 ? 

Definitely, I think. 

Since @brunoocasali will become the new maintainer of this repo soon, I will let him decide how we will proceed with this 🙂

**Comment by juchom** [comment]
Just replace

https://github.com/meilisearch/meilisearch-dotnet/blob/8d63ed44b0eabebcc9cd4fbc3a59dfc5831391f7/src/Meilisearch/Meilisearch.csproj#L4

with

```xml
<TargetFrameworks>netstandard2.1</TargetFrameworks>
```

**Comment by curquiza** [comment]
This issue (adding `client.UpdateKeyAsync()` method) should be done after https://github.com/meilisearch/meilisearch-dotnet/issues/221 :)

**Comment by sander1095** [comment]
Just my 2 cents.. I think using `netstandard2.0` is fine. 

Perhaps doing some usage research here would be a good idea. Ask users of meilisearch what .NET versions they use so you have a good idea.

Moving to .netstandard2.1 will gain you some newer c# features, but not many. I believe only c# 8 features, which has some cool stuff (nullable reference types)... but..

for new libraries, .netstandard is also already deprecated in favor of  `netx.0` (net5.0,net6.0) which is the way forward. 

Moving to `2.1` will mean that you can no longer support .NET framework, which is still used by legacy applications and a lot of those will never be upgraded. .NET framework will probably stay supported by MS forever.  Why deprecate this without clear benefit?

Framework definitely isn't the focus anymore, but there are still tons of application using it.

I think it would be better to just use netstandard2.0 until we reach a point where we see clear benefits to move away from `netstandard2.0` and just use `net6.0`or something so you gain stuff like c# 10

**Comment by juchom** [comment]
I think @sander1095's point of view is interesting and he is probably right with sticking to .NET Standard 2.0.

Going the .NET Standard 2.1 has the quality of dropping .NET Framework, brings ValueTask and missing bits of HttpClient.

Dropping .NET Framework right now is not a good idea, because you may miss some opportunities for Meilisearch on legacy apps.

Then benefits of switching from Task to ValueTask right now would not make sense.

The missing bits of HttpClient, I think we can add them easily.

I think that you should revert to .NET Standard 2.0 and we will add the missing parts to work with the server API. (Sorry for the bad advice)

**Comment by brunoocasali** [comment]
Since we rolled back to .NET Standard 2.0 how can we overcome this issue? Is something possible to do?

**Comment by juchom** [comment]
Yes, we will fix this 👍

**Comment by sander1095** [comment]
Could something like this be used? 

https://stackoverflow.com/questions/53982148/how-to-patch-data-using-system-net-http#53995041

**Comment by juchom** [comment]
I have created a quick PR if it has a chance to be shipped in the next release.

But, it will be a good idea to have an extension method for PATCH.
