### ISSUE TITLE
Drop .NET 2.0 support, upgrade the minimum to .NET 2.1

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#221]
Following this discussion: https://github.com/meilisearch/meilisearch-dotnet/issues/218

After some problems during the implementation of the v0.25, we decided internally that we should drop support of .net 2. The main reason is not based only on the v0.25 implementation problems but basically because we are supporting a version that is not supported even by Microsoft anymore.

The proposal here is to follow the .net core guidelines about EOL:
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Upgrade `meilisearch-dotnet` to ensure minimum support of `.NET Core 3.1`

- [ ] Update CI
- [ ] Update source code/tests
- [ ] Update README, CONTRIBUTING files

These concerns were raised originally here: #202 https://github.com/meilisearch/meilisearch-dotnet/issues/218#issuecomment-1020101386

**Comment by juchom** [comment]
CI and tests are already running  against .NET Core 3.1 so nothing to change.

I didn't see anything in README or CONTRIBUTING regarding .NET Standard 2.

You could just change this in #202 and it should works fine. If you have any issue let me know.

https://github.com/meilisearch/meilisearch-dotnet/blob/8d63ed44b0eabebcc9cd4fbc3a59dfc5831391f7/src/Meilisearch/Meilisearch.csproj#L4

with

```xml
<TargetFrameworks>netstandard2.1</TargetFrameworks>
```

**Comment by curquiza** [comment]
I think this is ready to implement now :)
