### ISSUE TITLE
Use DateTime when the property is related to dates instead of String

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-dotnet#224]
Move from `String` to `DateTime` in the following structures: 

- https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/Key.cs#L35-L45

Discussion related: https://github.com/meilisearch/meilisearch-dotnet/pull/219#discussion_r791036735

**Comment by anthkernan-dev** [comment]
I'm happy to take this

**Comment by brunoocasali** [comment]
@AK0785 thank you! 

Go ahead and comment here if you need some help! :D

**Comment by anthkernan-dev** [comment]
I've raised a PR - https://github.com/meilisearch/meilisearch-dotnet/pull/226
