### ISSUE TITLE
Documents methods should accept an int or a string

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#25]
With:

```c#
public class Movie
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

```c#
MeilisearchClient client = new MeilisearchClient("http://localhost:7700", "masterKey");
var index = client.CreateIndex("movies");
var documents = new Movie[] {
    new Movie {Id = 1, Name = "Batman"}
};
var updateStatus = await index.AddDocuments<Movie>(documents);
Movie movie = await index.GetDocument<Movie>(1);
```

I got the error "impossible to convert int into a string".
The `GetDocument` method should be able to accept an int or a string since MeiliSearch can accept a string or an int as a document identifier.

TODO:
- [ ] Fix in the code
- [ ] Add tests

**Comment by barbados-clemens** [comment]
I can take a look at this once I familiarize myself with the code. 

I assume we'd just want another method that takes an int along side the [current method](https://github.com/meilisearch/meilisearch-dotnet/blob/master/src/Meilisearch/Index.cs#L105)

like so
```csharp
public async Task<T> GetDocument<T>(int documentId)
{
    return await this._client.GetFromJsonAsync<T>($"/indexes/{Uid}/documents/{documentId}");
}
```

**Comment by curquiza** [comment]
If I'm not wrong, this should do the job 🙂

**Comment by barbados-clemens** [comment]
Would you want me to change all document methods that take a string or IEnumberable<string> and add an int version as well?

those would all include 
- GetDocument 
    - issue explicitly stating this one
- DeleteOneDocument
- DeleteDocuments

if yes, would you want me to change them all in this PR or submit a new PR for the Delete Methods?

I'm also now in the slack community as Barbados Clemens if you'd need to chat about it.

**Comment by curquiza** [comment]
So cool you are on the slack now 🙂

You can change all the methods in the same PR, thank you so much 😁 I m going to rename the issue accordingly
