### ISSUE TITLE
Use strong types to map lists instead of pure strings

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-dotnet#303]
The idea here is to implement `enum`'s to map lists eg:

- src/Meilisearch/Key.cs: `public IEnumerable<string> Actions { get; set; }`
- src/Meilisearch/QueryParamaters/TasksQuery.cs: `public List<string> Types { get; set; }` and `public List<string> Status { get; set; }`
- and others...

We may want to refactor this `src/Meilisearch/TaskInfo.cs`: `TaskInfoType`, `TaskInfoStatus` to a `static class` with public `const` fields.

**Comment by juchom** [comment]
Hi @brunoocasali,

Could you precise what you want to do here, it's not clear :

> The idea here is to implement `enum`'s to map lists eg:

You want enum at the begining

> We may want to refactor this `src/Meilisearch/TaskInfo.cs`: `TaskInfoType`, `TaskInfoStatus` to a static class with public const fields.

Then you want a class with const fields.

```csharp
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum TaskInfoStatus
    {
        Enqueued,
        Processing,
        Succeeded,
        Failed
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum TaskInfoType
    {
        IndexCreation,
        IndexUpdate,
        IndexDeletion,
        DocumentAdditionOrUpdate,
        DocumentDeletion,
        SettingsUpdate,
        DumpCreation
    }
```

`TaskInfoType` and `TaskInfoStatus` are already `enums` mapping from Meilisearch response as string.

What would you change for this two types ?

**Comment by brunoocasali** [comment]
Oh, sorry, let's make it clearer then:

In the `Keys.cs` we have the `Actions` field, which receives a list of Strings. That means I can add anything I want if they are a list of string like `new string[] { "a", "b", "c" }`, when I submit that to the server, I will receive an error and that is the thing I want to prevent.

Is there a way to accept a given set of values that the compiler will protect? 

`public IEnumerable<AvailableActions> Actions { get; set; }` or something like that?

The second part is related to the way enums work in C#, I thought it could be the right way to solve the problem I pointed out above.

**Comment by juchom** [comment]
Ok, I see what you want !

This issue was something I started to solve with `TaskInfoStatus` and `TaskInfoType` to avoid magic strings.

I also don't like magic strings :)
