### ISSUE TITLE
Add IndexesQuery to GetAllRawIndexesAsync method

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-dotnet#306]
The `GetAllRawIndexesAsync` function should support the same query params (`IndexesQuery`) as `GetAllIndexesAsync`

**Comment by radouane7** [comment]
what do you want to do with the IndexQuery after that ?

**Comment by brunoocasali** [comment]
The new Meilisearch version v0.28 added support to pagination in the indexes routes.

If you look close to the `GetAllIndexesAsync` you'll see that we support the pagination configuration. And the idea is to do the same in the `GetAllRawIndexesAsync` method as well.

https://github.com/meilisearch/meilisearch-dotnet/blob/cc6edddd447242493d85841e80a0bb401ab9da86/src/Meilisearch/MeilisearchClient.cs#L141-L149

**Comment by sander1095** [comment]
I'd like to do this one!

**Comment by alallema** [comment]
Hi @sander1095,
Thanks for the proposition it would be great! Don't hesitate to check how it's implemented in this method `GetAllIndexesAsync` to help you with it and don't hesitate if you had any questions 😊
