### ISSUE TITLE
Migrate test project to .NET 6

### ISSUE THREAD

**Issue by sander1095** [meilisearch/meilisearch-dotnet#331]
**Description**
Currently the test project uses `.NET Core 3.1`. [This is EOL in December](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). Because of this, I think it'd be a good idea to migrate the test project to .NET 6.0, which is LTS until 2024.

It'd be good to assume that the people that use this package either use .NET Framework (which is very old..) or the supported versions of .NET , which is going to be only .NET 6 starting December 20 2022. Meilisearch should also run their tests on .NET's LTS versions so they know the tests work correctly.

**Basic example**
1. Update the `TargetFramework` of `Meilisearch.Tests.csproj` to `net6.0`. 
2. Possibly update some packages (not required, but would be good to keep them up to date)
3. Done!

**Other**
None

**Comment by alallema** [comment]
Hi @sander1095,
Thanks for creating this issue, you are absolutely right EOL is coming soon but in general, we prefer to keep the old version as long as they are supported so please don't create a PR before the end of December 2022.
Thank you
