### ISSUE TITLE
Should `WaitForTasksAsync` throws by default ?

### ISSUE THREAD

**Issue by juchom** [meilisearch/meilisearch-dotnet#344]
I'm doing some review on the code and came to this method

https://github.com/meilisearch/meilisearch-dotnet/blob/b285f324aa94d725cefc70bd8673f42ecef277e3/src/Meilisearch/TaskEndpoint.cs#L70-L91

Don't you think that this method should return some sort of Result object like this instead of throwing :

```csharp
public class AwaitedTaskResult
{
     public Exception Exception { get; set; }
     public TaskResource TaskResource { get; set; }
     public bool HasCompleted => TaskResource.Status == TaskInfoStatus.Succeeded;
     public bool HasError => Exception != null;
}
```

The main idea is, that a task could take more time to finish on the server, but this is not an error from the server, it is just taking more time.

Instead of writing

```csharp
try
{
   await client.WaitForTaskAsync(taskUid);
}
catch (Exception ex)
{
   // do something with the exception
}
```

We could write

```csharp
var res = await client.WaitForTaskAsync(taskUid);
if (res.HasError)
  throw res.Exception;
```

Doing this avoid using exceptions for the control flow, this avoir using try catch blocks if they just want to silent the error.

The main question here is, should this method throws when timeout is reached instead of always returning an object like `AwaitedTaskResult` ?

**Comment by alallema** [comment]
Hi @juchom,
Thank you very much for opening this issue, it is very interesting. Indeed, it is not a server error but there is no specific reason for it to take time and most importantly this method was created exclusively for testing and is not intended to be used outside. However, I think this question could be of interest to the rest of the @meilisearch/integration-team

**Comment by brunoocasali** [comment]
Agreed @alallema. In most of our SDKs, we have a similar piece of code, but we use it only to test, and we try not to advertise it too much because I think this could be very dangerous if the developer is not cautious.

**Comment by juchom** [comment]
Actually, developers may want to wait for a task (Meilisearch side) to finish and know the result.

If Meilisearch is on error for some reason, we have to know something wrong happened.

This polling method is interesting for developers, this avoid them to develop their owns.

I agree with you, this one is dangerous and mainly because it throws if something went wrong. Having it always returning an object with some helpers methods to know why the final result is a failure would be a nice option.

We could also had a boolean parameter `bool throwOnError = false` that can be turned on for testing to avoid extra checks in tests.

```csharp
 public async Task<AwaitedTaskResult> WaitForTaskAsync( 
     int taskUid, 
     double timeoutMs = 5000.0, 
     int intervalMs = 50, 
     bool throwOnError = false,
     CancellationToken cancellationToken = default) 
```

**Comment by alallema** [comment]
Hi @juchom,
I really like the idea of adding `bool throwOnError = false` but I'm afraid that it will encourage contributors to use this function. Again, `Meilisearch` is asynchronous and this function will force it to be synchronous by making sure the operation is completed, which could be dangerous in production. So we don't recommend it at all, except for testing purposes.
But we could totally think of a way to handle and return errors differently, I agree with that.

**Comment by juchom** [comment]
I understand why you want to encourage a fire and forget strategy for async server side operations.

In this case, should this method stay in the client project ? If no, it can be moved to the unit tests project, if you want to prevent its usage.

**Comment by alallema** [comment]
Since this question has been forwarded to another repo and discussed, I'll close it.
