### ISSUE TITLE
Creating tenant tokens fails in .net 7 because of key size to small

### ISSUE THREAD

**Issue by andtii** [meilisearch/meilisearch-dotnet#363]
**Description**
Creating tenant tokens fails in .net 7 

**Expected behavior**
Creating tenant tokens to work

**Current behavior**
Exceptions when creating tenant tokens.

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/1434571/203777776-885f6568-f3a6-4454-a9bb-5bd4eb3a36b2.png)

**Environment (please complete the following information):**
- OS: Windows
- Meilisearch version: 0.29.2
- meilisearch-dotnet version: 0.12.1

**Comment by andtii** [comment]
Does not help with a longer key, seems internally using 80 always

![image](https://user-images.githubusercontent.com/1434571/203778925-a78e479c-14a0-4eeb-bdb7-d8cc0429545e.png)

**Comment by andtii** [comment]
It worked when passing it as a third argument

![image](https://user-images.githubusercontent.com/1434571/203779271-ff1d278a-942c-49c9-85f2-aa3f43dfe4b6.png)

**Comment by alallema** [comment]
Hi @andtii,
Thanks for raising this issue, sorry for the delay, I was on sick leave I will check this as soon as possible 😉

**Comment by juchom** [comment]
Hello,

This is not an issue with .Net 7 or the client itself, the exception is giving you all the information :

> IDX10653: The encryption algorithm 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha256' requires a key size of at least '128' bits. Key '[PII of type 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', is of size: '80'. (Parameter 'key')

When you don't set the third parameter, it will use by default the master key for signing the token. From you're exception I can see your master key is 10 characters long. To sign a token with hmac-sha256 you need a master key that is at least 16 characters long.

@alallema it would be good to not allow master keys under 16 characters when creating an instance of Meilisearch. If it's ok with your team, we can then double check on the client that the master is long enough to follow the spec of hmac-sha256.

**Comment by alallema** [comment]
Sorry for the delay,
>When you don't set the third parameter, it will use by default the master key for signing the token. From you're exception I can see your master key is 10 characters long. To sign a token with hmac-sha256 you need a master key that is at least 16 characters long.

Exact! Thank @juchom to raise it

>@alallema it would be good to not allow master keys under 16 characters when creating an instance of Meilisearch. If it's ok with your team, we can then double check on the client that the master is long enough to follow the spec of hmac-sha256.

The problem is that people who don't need to generate a token will also have to create a key of at least 16 characters. And this may complicate the use of the client, so I'm not sure I'm for it.
Maybe put a Warning could be enough

**Comment by alallema** [comment]
I discussed this with the team, and we came to the point that the best solution was that the generateTenantToken method should return an exception that checks the master key.
Thanks again @juchom

**Comment by alallema** [comment]
Thanks to @juchom for his investigation:

This error is caused by the `Encoding.ASCII`, which needs at least 16 characters to transform the key into []bytes
The length of the key is already checked but wrongly:
```cs
            if (String.IsNullOrEmpty(apiKey) || apiKey.Length < 8)
            {
                throw new MeilisearchTenantTokenApiKeyInvalid();
            }
```
There are two solutions:
- Change the check of the length to 16 
- Find another way to encode instead of using the `Encoding.ASCII.GetBytes()` method

TO DO:
- [ ] Either change the length condition or the encoding method
- [ ] Add tests
