### ISSUE TITLE
Reduce code duplication

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-dotnet#371]
Given the adoption of the `ToQueryString()` extension method, we have duplicated this piece of code everywhere:

```cs
var uri = "tasks";
if (query != null)
{
   uri = $"{uri}?{query.ToQueryString()}";
}
```

We can put this logic inside of the ToQueryString() and start to receive a non-required argument to the method.

```cs
query.ToQueryString("tasks"); // which will become "tasks?myParam=123"
query.ToQueryString(); // which will become "myParam=123
```

**Comment by kashifsoofi** [comment]
Can I work on this please?
