### ISSUE TITLE
Localization issue when get the result 

### ISSUE THREAD

**Issue by Ahmad-Nour** [meilisearch/meilisearch-dotnet#384]
Hi, i can't get the result in other language, I used MeiliSearch with Strapi and need to do search and get the result  in other language..

- Meilisearch version: [e.g. v0.30.4]
- meilisearch-dotnet version: [e.g v0.11.0.0]

**Comment by oluademola** [comment]
Hello @Ahmad-Nour 

Very sorry for the delayed response. Could you please clarify your current data configuration? Do you have a field per language in your documents? Do you have an index per language?

Thanks

**Comment by Ahmad-Nour** [comment]
Hello @oluademola  
Thnak you for your response, I solved the issue yasterday, the issue was in my configureations sorry about that ...
