### ISSUE TITLE
Add generic type to `TaskInfoType` to handle new `Task` type

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-dotnet#385]
**Description**
All types of tasks are grouped in an enum `TaskInfoType`
```c#
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum TaskInfoType
    {
        IndexCreation,
        IndexUpdate,
        ...
        IndexSwap
    }
```
But if a new [task type is created](https://github.com/meilisearch/meilisearch/issues/3162) there will be a break.

**Suggestion**
To avoid breaking when a [new `Task` type is created](https://github.com/meilisearch/meilisearch/issues/3162), it would be great to create a generic type such as `unknown` that will handle all types that do not belong to the existing enum.

**Comment by postmeback** [comment]
I have added the "Unknown" type in the enum. 

What next? Updating the tests @alallema

**Comment by curquiza** [comment]
Hello @postmeback 

I don't see th Unknown type
https://github.com/meilisearch/meilisearch-dotnet/blob/f7f92b3bb7e3612fb86cb017a839575bb6678cea/src/Meilisearch/TaskInfo.cs#L106

**Comment by postmeback** [comment]
In my branch, I have added

https://github.com/postmeback/meilisearch-dotnet/blob/main/src/Meilisearch/TaskInfo.cs

**Comment by postmeback** [comment]
Shall I improve the **tests** next ?

**Comment by curquiza** [comment]
Yes, please, always add/improve the tests if possible when adding new things to the repo 😊
