### ISSUE TITLE
Expected GetIndexAsync to return null when not found, actually throws an exception

### ISSUE THREAD

**Issue by rude-seagull** [meilisearch/meilisearch-dotnet#386]
**Description**

In `MeilisearchClient` the `GetIndexAsync` method throws an exception of type `MeilisearchApiError` when the index is not found.

**Expected behavior**

The documentation written specifies that `null` will be returned in case of a non existing index.

**Screenshots or Logs**

Line 168

```
/// <summary>
/// Gets an index with the unique ID.
/// </summary>
/// <param name="uid">Unique identifier of the index.</param>
/// <param name="cancellationToken">The cancellation token for this call.</param>
/// <returns>Returns Index or Null if the index does not exist.</returns>
public async Task<Index> GetIndexAsync(string uid, CancellationToken cancellationToken = default)
{
   return await Index(uid).FetchInfoAsync(cancellationToken).ConfigureAwait(false);
}
```

**Environment (please complete the following information):**
- OS: docker pull
- Meilisearch version: v.0.30.0
- meilisearch-dotnet version: v0.13.0

**Comment by alallema** [comment]
Hi @rude-seagull,
Thanks for raising this issue 😊
