### ISSUE TITLE
Use JsonContent instead of StringContent in HttpExtensions.PrepareJsonPayload

### ISSUE THREAD

**Issue by jtmueller** [meilisearch/meilisearch-dotnet#394]
**Description**
Memory usage and performance would improve if this library used JsonContent instead of StringContent when serializing to JSON for use with HttpClient. This is because JsonContent serializes directly to UTF-8 bytes which are written directly to the HttpClient output stream without storing the entire document in memory at once. Using StringContent forces the object to be serialized to a UTF-16 string in memory, which will need to be garbage-collected later, and then forces the UTF-16 string to be converted to UTF-8 bytes before it can be written to the HttpClient output stream.

**Basic example**

```csharp
private static StringContent PrepareJsonPayload<T>(T body, JsonSerializerOptions options = null)
{
    options ??= Constants.JsonSerializerOptionsWriteNulls;
    var payload = JsonContent.Create(body, new MediaTypeHeaderValue("application/json"), options);
    payload.Headers.ContentType.CharSet = string.Empty;

    return payload;
}
```

**Comment by alallema** [comment]
Hi @jtmueller,
Thank you so much for bringing this up! 🔥 It does indeed seem like a very good improvement although I am not familiar with this subject.
It works perfectly if I actually replace the function with your code:
```csharp
private static JsonContent PrepareJsonPayload<T>(T body, JsonSerializerOptions options = null)
{
    options = options ?? Constants.JsonSerializerOptionsWriteNulls;
    var payload = JsonContent.Create(body, new MediaTypeHeaderValue("application/json"), options);
    payload.Headers.ContentType.CharSet = string.Empty;

    return payload;
}
```
