### ISSUE TITLE
Error on fields of PaginatedSearchResult.cs

### ISSUE THREAD

**Issue by molinellinacho** [meilisearch/meilisearch-dotnet#400]
**Description**
There is an error on fields of PaginatedSearchResults. 

**Expected behavior**
There is a field called "total" that is not correct, and there are two fields that are missing: totalPages and totalHints. This is important for pagination with page numbers, because they are the exact number of results and pages.

**Comment by brunoocasali** [comment]
Hi @imolinelli, thanks for your report!

You're completely right. I'm going to submit a fix to this issue ASAP.
