### ISSUE TITLE
search query

### ISSUE THREAD

**Issue by imandoostie** [meilisearch/meilisearch-dotnet#449]
can somebody please gave me an example of how to write a search query in c#?

i want a search query like this '"john" and oliver' meaning john should be present and oliver could be optional 
also is there a way to turn of case sensitivity ?

another question is how about searching in other language ? is there library for us to use ? and if not how meilisearch engine gonna tokenize those words ?

**Comment by alallema** [comment]
Hi @imandoostie,
All the examples are in the [documentation](https://www.meilisearch.com/docs/reference/api/search) under the C# tab.
For the rest of your questions, and if you have any others, I suggest you join our [Discord](https://discord.com/invite/meilisearch), where you can find the help you need.
As this is not a problem related to this repository, I will close this issue.
