### ISSUE TITLE
SearchQuery missing AttributesToSearchOn

### ISSUE THREAD

**Issue by SKeeneCode** [meilisearch/meilisearch-dotnet#455]
**Description**

`SearchQuery` does not appear to have an option for customizing what attributes to search on.

This feature is described in the documentation here:

https://www.meilisearch.com/docs/reference/api/search#customize-attributes-to-search-on-at-search-time

I can see the only examples at the time of writing are CURL and PHP so perhaps this is a recently added feature to meilisearch of which the integrations are yet to catch up.

**Basic example**

Expect to be able to use it like so:

```
var query = new SearchQuery
        {
            Filter = $"forumID = {forumId}",
            AttributesToSearchOn = new[] {"title","text"},
            AttributesToHighlight = new[] {"title","text"},
            AttributesToCrop = new [] {"text:30"},
        };
```

**Comment by brunoocasali** [comment]
Hi @SKeeneCode 

Indeed, this feature was out in Meilisearch v1.3 (the latest version) and the same request is being tracked here: https://github.com/meilisearch/meilisearch-dotnet/issues/457

Unfortunately, we don't have enough human resources to work on this request. So it would be appreciated if someone else came and do it.

**Comment by SKeeneCode** [comment]
Hey @brunoocasali 

Thanks for raising an issue for this request. I've opened a PR here for it:

https://github.com/meilisearch/meilisearch-dotnet/pull/463
