### ISSUE TITLE
Add support for custom JSON serialization options

### ISSUE THREAD

**Issue by exepirit** [meilisearch/meilisearch-dotnet#475]
Hello.

**Description**
The current implementation of the `SearchAsync` method in the `Index` class uses hardcoded JSON serialization options ([src](https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/Index.Documents.cs#L543)), which makes it difficult to use custom serialization options.

The implementation of the `AddDocumentsAsync` method in the `Index` class also not pass a `JsonSerializationOptions`, thus `HttpExtensions` applies hardcoded options ([src](https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/Extensions/HttpExtensions.cs#L87)).

Is it no possible to use custom converters or use different naming policy.

I think that a ability to customize objects serialization is important for integration Meilisearch in existing projects, especially in the projects with complex data models or custom JSON serialization policies.

**Basic example**
```csharp
var options = new JsonSerializerOptions
{
    Converters = { new BaseClassConverter() },
};

var client = new MeilisearchClient("http://localhost:7700", "masterKey", options);
```

It one of many examples of desired implementations. C# is not my main programming language, so i'm not sure that is a best example of the feature interface.

**Comment by liven-maksim-infotecs** [comment]
I aggree with the previous speaker. I have polymorphic classes and wanna write and read data via abstract base class. I can't use attributes because models are from nuget package (external contracts).

**Comment by curquiza** [comment]
Hello everyone here, thanks for the suggestion and your participation!

If I'm correct, this will not impact the users who don't need this option, this would be only an addition to the library (not breaking).

@juchom if you are around, I would love to have your opinion on this 😊 
So far, since the community seems to need it, I would go for a "let's do it!"

**Comment by juchom** [comment]
Hello,

Actually, this is a good idea, especially with dotnet 8 having new naming policies that may better fit some use cases.

> If I'm correct, this will not impact the users who don't need this option, this would be only an addition to the library (not breaking).

You are almost correct :)

It will have no impact if the defaults are kept. You will have to make sure that creating a client like we do now will keep the same behaviours.

**Comment by juchom** [comment]
Actually it's a dupe of #311 I already opened 🤣

**Comment by exepirit** [comment]
> If I'm correct, this will not impact the users who don't need this option, this would be only an addition to the library (not breaking).

Yes, this is not breaking change and not impact the users who use meilisearch-client before. I think this should be an optional parameter in client `ctor` or something similar.

**Comment by curquiza** [comment]
Oh yes, indeed a duplication! Closing this one in favor of #311 then 😄

**Comment by exepirit** [comment]
ok, closed as dup
