### ISSUE TITLE
Replace the GitHub action to publish to Nugget

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#480]
Currently, in this repo we publish the library to Nugget, and we use this archived GitHub action: https://github.com/brandedoutcast/publish-nuget

We need to modify [this file](https://github.com/meilisearch/meilisearch-dotnet/blob/main/.github/workflows/publish.yml) to do the same by using dotnet CLI
See: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry

**Comment by kashifsoofi** [comment]
Can I please take this?

**Comment by curquiza** [comment]
Hello @kashifsoofi 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

For your information, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊
