### ISSUE TITLE
Tests suite randomly fails

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#50]
See this job
https://github.com/meilisearch/meilisearch-dotnet/runs/961819954?check_suite_focus=true

**Comment by satish860** [comment]
This is because of use of a streaming library in the HTTP Client. We should go back to use the default one.  Also I was a able to replicate the failure using Rider run test

**Comment by curquiza** [comment]
Do you think this is easy to fix @satish860? 🙂
Or can't we just adapt the tests to work with a streaming library?

**Comment by curquiza** [comment]
This issue seems to be fixed now after we updated the tests.
I will re-open this issue if needed, or if someone asks for it
