### ISSUE TITLE
SearchQuery.FacetFilters property is not available

### ISSUE THREAD

**Issue by themisir** [meilisearch/meilisearch-dotnet#54]
As described in [this section](https://docs.meilisearch.com/guides/advanced_guides/faceted_search.html#using-facets) I have to specify `facetFilters` parameter to narrow search result. But I think this feature is not available.

**Comment by curquiza** [comment]
Hello @TheMisir!

The facets are indeed not handled yet in this package! Thanks a lot for starting it 😁

In this issue (https://github.com/meilisearch/meilisearch-dotnet/issues/17) you can see the settings are missing, it means the `attributesForFacetting` are missing.

The `facetsDistribution` parameter during the search is also missing. I'm going to open an issue.
