### ISSUE TITLE
[v1.9] Support `rankingScoreThreshold` search parameter

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#544]
*Following this [central issue](https://github.com/meilisearch/integration-guides/issues/301)*

This is related to a newly introduced feature in [Meilisearch v1.9.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.9.0): the `rankingScoreThreshold` search parameter.

Refer to [docs for more information](https://www.meilisearch.com/docs/reference/api/search#ranking-score-threshold).

- [ ] Ensure the library can accept the new `rankingScoreThreshold` search parameter.
- [ ] ⚠️ Add integration tests ⚠️
- [ ] Update the `.code-samples.meilisearch.yaml`
    - [ ]  Add `search_parameter_reference_ranking_score_threshold_1` key and “translate” the following curl example by using the newly added methods: https://github.com/meilisearch/documentation/blob/04f26a35771305378ed0a506f4d60ef06d07bd7e/.code-samples.meilisearch.yaml#L1344

**Comment by danFbach** [comment]
@curquiza this looks easy enough to implement, and I would like to be able to use it.
What are the expectations for new tests?
Something like a Search test that would return multiple results without the Threshold but, with a threshold applied, returns fewer? What else?

And as far as updating `.code-samples.meilisearch.yaml` - is that something done internally, and you just want an example of it's usage added to the README of this repo?

**Comment by curquiza** [comment]
> Something like a Search test that would return multiple results without the Threshold but, with a threshold applied, returns fewer? What else?

Would be perfect

> And as far as updating .code-samples.meilisearch.yaml - is that something done internally, and you just want an example of it's usage added to the README of this repo?

Nope, I need you to update the [code sample file](https://github.com/meilisearch/meilisearch-dotnet/blob/main/.code-samples.meilisearch.yaml) of this repo with a new entry: `search_parameter_reference_ranking_score_threshold_1`, and put the same example than the one that has been linked in the issue, but not with `curl` but in dotnet 😊

**Comment by danFbach** [comment]
sorry, I missed the code-samples file since it wasn't shown in the solution explorer. 🤦‍♂️ lol
Anyway, sending PR now.

**Comment by curquiza** [comment]
Trying to review your PR next week @danFbach 
thank you for your contributions ❤️
