### ISSUE TITLE
EstimatedTotalHits Removed 

### ISSUE THREAD

**Issue by migueltarga** [meilisearch/meilisearch-dotnet#577]
**Description**
The Search was refactored at some point to use https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/ISearchable.cs instead of https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/SearchResult.cs and some properties were left out, like **EstimatedTotalHits**

**Comment by danFbach** [comment]
I also encountered this. sent a pull request. hopefully it's sufficient.

**Comment by migueltarga** [comment]
Not an issue based on https://github.com/meilisearch/meilisearch-dotnet/pull/578
The documentation is outdated.

Thank you  @danFbach
