### ISSUE TITLE
Design decision about passing HttpClient by user.

### ISSUE THREAD

**Issue by Nothing-Works** [meilisearch/meilisearch-dotnet#6]
As a user, I prefer not to pass `HttpClient` by myself.

> Use it with proper Http Client Factory.

I saw this comment and understand it, but I still think it's an extra step to get it up and running.

**Comment by curquiza** [comment]
Hello @Nothing-Works!

Yes, this issue is an extra step but seems to be a good one 😉 If I'm not wrong, an external contributor did the same on the PHP SDK.
Everyone is welcome to do it 🙂

NB: we have to provide an HTTP client by default if the user does not want to use his/her own HTTP Client.

**Comment by satish860** [comment]
Well, the idea here is to use it as a Typed HttpClient as part of service collection, Well we can use a default value if possible. 

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

**Comment by satish860** [comment]
@Nothing-Works We have a new overload without the dependency on Httpclient. Hope that closes the issue . @curquiza I have not published or bumped the version. Can we pick it up

**Comment by curquiza** [comment]
I'm not sure to get it well, so I ask confirmation: is the new usage (see the getting started in the README) okay with you @Nothing-Works? 🙂 Can we close this issue then?

**Comment by Nothing-Works** [comment]
@satish860 @curquiza yes this is very easy to get started and consistent with other adapters well done thanks.
