### ISSUE TITLE
Code for Searchable attributes

### ISSUE THREAD

**Issue by appa1303** [meilisearch/meilisearch-dotnet#60]
Hi, 

Can you add code to get/set Searchable attributes
I suggest the following to go into Index.cs 

`        
        /// <summary>
        /// Update searchable attributes.
        /// </summary>
        /// <param name="attributes">strings that contains searchable attributes sorted by order of importance (arranged from the most important attribute to the least important attribute).</param>
        /// <returns>Returns the updateID of this async operation.</returns>
        /// <remarks>Even if the document class properties are in upper/mixed case the attributes should be in lower case.</remarks>
        public async Task<UpdateStatus> UpdateSearchableAttributes(IEnumerable<string> attributes)
        {
            var responseMessage = await this.client.PostAsJsonAsync($"/indexes/{this.Uid}/settings/searchable-attributes", attributes);
            return await responseMessage.Content.ReadFromJsonAsync<UpdateStatus>();
        }

        /// <summary>
        /// Get searchable attributes.
        /// </summary>
        /// <returns>An Ienumerable of strings that contains searchable attributes sorted by order of importance (arranged from the most important attribute to the least important attribute).</returns>
        public async Task<IEnumerable<string>> GetSearchableAttributes()
        {
            return await this.client.GetFromJsonAsync<List<string>>($"/indexes/{this.Uid}/settings/searchable-attributes");
        }

`

**Comment by curquiza** [comment]
Hello @appa1303! Thanks for your suggestion!
I'm currently working on a PR to get/update/reset all the settings, so the possibility to get the searchable attributes 🙂
Once it's merged I will let you know here!

**Comment by curquiza** [comment]
Hello @appa1303, the [v0.3.1](https://github.com/meilisearch/meilisearch-dotnet/releases/tag/v0.3.1) is out and allows you to update your settings (so your searchable attributes).

```cs
var index = await this.client.GetOrCreateIndex("indexUID");
Settings newSettings = new Settings
{
        SearchableAttributes = new string[] { "name", "genre" },
};
UpdateStatus update = await index.UpdateAllSettings(newSettings);
```

I close this issue 🙂 Feel free to re-open it if something is not clear
