### ISSUE TITLE
The UpdateDocuments method should be a partial update

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#67]
Currently when doing this test:

```c#
var indexUID = "BasicDocumentsUpdateTest";
Index index = await this.client.GetOrCreateIndex(indexUID);

// Add the documents
UpdateStatus update = await index.AddDocuments(new[]
{
    new Movie { Id = "1", Name = "Batman", Genre = "Action" },
    new Movie { Id = "2", Name = "Superman" }
});

// Update the documents
update = await index.UpdateDocuments(new[] { new Movie { Id = "1", Name = "Ironman" } });

// Check the documents have been updated and added
var docs = await index.GetDocuments<Movie>();
Assert.Equal("1", docs.First().Id);
Assert.Equal("Ironman", docs.First().Name);
Assert.Equal("Action", docs.First().Genre);
Assert.Equal("2", docs.ElementAt(1).Id);
Assert.Equal("Superman", docs.ElementAt(1).Name);
docs.ElementAt(1).Genre.Should().BeNull();
```

The `Assert.Equal("Action", docs.First().Genre);` line fails because `Genre` is `null` but it should not be. The [add-or-update-documents route](https://docs.meilisearch.com/references/documents.html#add-or-update-documents) should be a **partial update**, so the value a `Genre` should still be `"Action"`.

**Comment by huseyinsimsekk** [comment]
Can we solve this using PATCH method?

**Comment by curquiza** [comment]
Hello @huseyinsimsekk 
MeiliSearch does not provide any `PATCH` method.
The SDK uses the `PUT` route `add-or-update-documents`, but the bad behavior is the fault of the SDK because even if you send only (following the example above):

```c#
await index.UpdateDocuments(new[] { new Movie { Id = "1", Name = "Ironman" } });
```
it will send actually

```c#
await index.UpdateDocuments(new[] { new Movie { Id = "1", Name = "Ironman", Genre = null } });
```

because `Movie` is defined like this:

```c#
public class Movie
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public string Genre { get; set; }
    }
```

**=> the SDK should only send the fields that the user sends to make MeiliSearch work correctly**

I hope this is clearer, sorry, my description wasn't, obviously
