### ISSUE TITLE
Set SearchQuery.Filters type to be a string

### ISSUE THREAD

**Issue by XREvo** [meilisearch/meilisearch-dotnet#85]
The MeiliSearch documentation specify that the SearchQuery.Filters property is of type string and not array of string : https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#filters

The associated type of this property should be changed and test updated to cover this. Without this change, it's impossible to use this field (at least with the version 0.17.0 that i have on my laptop).

Note : I'll take time to do a PR in order to fix that.

**Comment by curquiza** [comment]
Hello @XREvo, thanks for your time for writing down this issue and for the PR! I'm going to review it right now!
