### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dotnet#9]
We should add a linter to this project, at least for the code style.

For example, I can see here the same kind of method but with not the same style (especially in the name of the function):

https://github.com/meilisearch/meilisearch-dotnet/blob/086c738d2254435687e7f45db2996fd7826d11d4/tests/Meilisearch.Tests/DocumentTests.cs#L23-L43

The goal is to provide a better environment for contribution 🙂

I'm not a .NET dev, so I'm not aware of the lint tools in .NET. What do you suggest?

NB: I'm adding an editorconfig file in this PR #8 but it's just about general style indentation.

**Comment by satish860** [comment]
@curquiza Generally we use Stylecop analyzer in the .net project with the connection of editor config.  https://github.com/DotNetAnalyzers/StyleCopAnalyzers
This will allow the coding style to be uniform. Let me know if this can solve the requirement, I can get it added .

**Comment by curquiza** [comment]
Ok good to know! :)
The goal is to be able to add this linter check in the CI so that a PR with linter errors cannot pass 🙂

**Comment by satish860** [comment]
Yes this will be added as part of the build so even CI fails if code doesn't follow the same.

**Comment by curquiza** [comment]
The linter should also solve this kind of issue in [this file](https://github.com/meilisearch/meilisearch-dotnet/blob/master/src/Meilisearch/SearchQuery.cs):

```c#
        public int? cropLength { get; set; }
        public string AttributesToHighlight { get; set; }
```

Some attributes are in upper CamelCase, but others are not.
